language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  global:
   - DRF="djangorestframework==3.4.6"
   - WQ_APP="wq.app==1.0.0b1"
   - WQ_DB="wq.db==1.0.0b1"
  matrix:
   - DJANGO="django==1.8.14"
   - DJANGO="django==1.9.9"
   - DJANGO="django==1.9.9" LINT=1
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install $WQ_APP
 - pip install $WQ_DB
 - pip install flake8
 - pip install psycopg2
 - pip install .
script:
 - ./runtests.sh
